
name: CI/CD Workflow

on:
  push:
    branches:
      - 'master'
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          # Deployment steps for the master branch
          # Replace this with your deployment script

      - name: Notify
        if: always()
        run: |
          echo "Workflow completed on branch: ${{ github.ref }}"
